services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=AnalysisDatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'


  adminer:
    image: 'adminer'
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    restart: always
    ports:
      - '8888:8080'
